version: "3.8"
services:
  # configuracion del servidor alpine
  java_app:
    container_name: java_app
    image: tnosql-rest:1.0
    build: .
    links:
        - mongorest
        - redis
    ports:
      - "8080:8080"
    environment:
        - MONGO_HOST=mongorest
        - MONGO_PORT=27017
        - MONGO_DB=tnosqlv1
        - MONGO_USER=root
        - MONGO_PASS=password
        - REDIS_HOST=redis
        - REDIS_PORT=6379
    depends_on:
        - mongorest
        - redis
  mongorest:
    # docker pull mongo:7.0.2
    image: mongo
    container_name: mongorest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - ./database/mongodb/db:/data/db
      - ./database/mongodb/dev.archive:/Databases/dev.archive
      - ./database/mongodb/production:/Databases/production
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"