server:
  port: 8080
spring:
  cache:
    type: redis
  data:
    mongodb:
      # para localhost
#      password: password
#      host: localhost
#      port: 27017
#      uri: mongodb://localhost:27017/tnosqlv1
#    redis:
#      host: localhost
#      port: 6379
      # para docker
      authentication-database: admin
      database: ${MONGO_DB}
      server: localhost
      port: ${MONGO_PORT}
      username: ${MONGO_USER}
      password: ${MONGO_PASS}
      host: ${MONGO_HOST}
      uri: mongodb://root:password@mongodb:27017/tnosqlv1?authSource=admin
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
redis:
  timeout: ${REDIS_TIMEOUT}
  maximumActiveConnections: ${REDIS_MAX_ACTIVE}
# confirguacion de la ruta del swagger
springdoc:
  swagger-ui:
    path: /v1/swagger.html