spring:
  data:
    mongodb:
      # para localhost
      password: password
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/tnosqlv1
    redis:
      host: localhost
      port: 6379
    # para docker
#    mongodb:
#      authentication-database: admin
#      database: tnosqlv1
#      username: root
#      password: password
#      host: locahost
#      port: 27017
#      uri: mongodb://root:password@mongodb:27017/tnosqlv1?authSource=admin
#    redis:
#      host: ${REDIS_HOST}
#      port: 6379
# confirguacion de la ruta del swagger
springdoc:
  swagger-ui:
    path: /v1/swagger.html